### ISSUE TITLE
Pricing Table 

### ISSUE THREAD

**Issue by zellwk** [ga-students/wdi-sg-organisers#12]
Might be interesting to code a pricing table like this. 

![screen shot 2016-01-05 at 9 46 10 pm](https://cloud.githubusercontent.com/assets/3607637/12116645/4ee6a660-b3f6-11e5-8d40-86c44bd3ce71.png)

**Comment by caalberts** [comment]
For copy and pasting:

```
Single
For individual creatives. No subscription, you only pay once & it's forever yours.
$89 $109
1 License
Content Editor
Fully Responsive
Custom Fontsets
Retina Ready
Fullscreen Cover
Dribble Module
Code Module
Private Projects
& more

Studio
Great for small studios and agencies with advanced pro tools. You only pay once.
$128 $159
Design with Blocks
Mailchimp Module
Instagram Module
1 License
Content Editor
Fully Responsive
Custom Fontsets
Retina Ready
Fullscreen Cover
Dribble Module
Code Module
Private Projects
& more

Business
Run Semplice on 10 domains and use it for your client projects commercially.
$399 $499
Business includes all features of our Studio version including 10 licenses for commercial use.
You can update from Single or Studio to Business at any time.
```

**Comment by jsstrn** [comment]
Thanks @caalberts! :+1: :+1:

**Comment by caalberts** [comment]
typed by @jerrygraced. I just copied and pasted

**Comment by jsstrn** [comment]
### Colors
box: #F2F1F1 yellow button: #FFD800

**Comment by cbas** [comment]
@zellwk 's solution:
http://codepen.io/zellwk/pen/bEqWQM?editors=010

**Comment by yongjun21** [comment]
http://codepen.io/yongjun21/pen/eJvWXw

**Comment by tongrhj** [comment]
More Jade and Stylus http://codepen.io/tongrhj/pen/adJWgv

**Comment by cbas** [comment]
@yongjun21 :+1: Nicely done! Just a few small observations:
- `.plan-features` and `ul.plan-features` are duplicated
- `flex-basis: 1px;` on `.plan` to make the columns evenly wide.

To fix the Safari issues try:
```css
.plan-features {
  flex: auto;
  padding-left: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
}
.plan-features li {
  width: 100%;
}
```

**Comment by cbas** [comment]
@tongrhj Excellent factoring in the Jade code. Love it. :+1: 

The columns look a bit stretched between 1024px and ~600px. Would give them a `max-width`.

Below ~400px the checkmarks stop being outside the list items, spoiling the perfect alignment.

Looks like there's too much horizontal padding for small phone screens. Precious pixels! :scream:
