### ISSUE TITLE
Slideshow Background

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-organisers#13]
[![Background Scroll Demo](http://i.imgur.com/SUHL7c9.gif)](http://i.imgur.com/SUHL7c9.gifv)

Hints:
```
background-attachment
background-size
background-repeat
background-position
```

**Spoiler Alert: Do not view until utterly stuck and all hope has been lost**

Live Demo:
http://tutsplus.github.io/create-a-masked-background-effect-with--background-attachment--fixed--/

**Comment by jsstrn** [comment]
Copy and paste:
```
        <h2>Scroll Down and Watch What Happens</h2>
        <p>Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, `and what is the use of a book,' thought Alice `without pictures or conversation?'</p>
        <p>So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy- chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her.</p>
        <p>There was nothing so very remarkable in that; nor did Alice think it so very much out of the way to hear the Rabbit say to itself, `Oh dear! Oh dear! I shall be late!' (when she thought it over afterwards, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural); but when the Rabbit actually took a watch out of its waistcoat- pocket, and looked at it, and then hurried on, Alice started to her feet, for it flashed across her mind that she had never before seen a rabbit with either a waistcoat-pocket, or a watch to take out of it, and burning with curiosity, she ran across the field after it, and fortunately was just in time to see it pop down a large rabbit-hole under the hedge.</p>
        <p>In another moment down went Alice after it, never once considering how in the world she was to get out again.</p>
        <p>The rabbit-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep well.</p>
        <p>Either the well was very deep, or she fell very slowly, for she had plenty of time as she went down to look about her and to wonder what was going to happen next. First, she tried to look down and make out what she was coming to, but it was too dark to see anything; then she looked at the sides of the well, and noticed that they were filled with cupboards and book-shelves; here and there she saw maps and pictures hung upon pegs. She took down a jar from one of the shelves as she passed; it was labelled `ORANGE MARMALADE', but to her great disappointment it was empty: she did not like to drop the jar for fear of killing somebody, so managed to put it into one of the cupboards as she fell past it.</p>
        <p>`Well!' thought Alice to herself, `after such a fall as this, I shall think nothing of tumbling down stairs! How brave they'll all think me at home! Why, I wouldn't say anything about it, even if I fell off the top of the house!' (Which was very likely true.) </p>
```

**Comment by cbas** [comment]
@jsstrn [Emmet support in Codepen](http://blog.codepen.io/documentation/editor/tab-triggers/)

**Comment by jsstrn** [comment]
@cbas sweet! :+1:

**Comment by jsstrn** [comment]
**Spoiler Alert**
If you're finding it especially hard and you want the official tutorial to follow along, see this [link](http://webdesign.tutsplus.com/tutorials/create-a-masked-background-effect-with-css--cms-21112). If you want to challenge yourself and figure this out on your own **do not click on the link**.

**Comment by caalberts** [comment]
Try this nth-child calculator to choose specific children http://nth-calculator.com/

**Comment by cbas** [comment]
http://codepen.io/cbas/pen/mVWaVv?editors=110

**Comment by caalberts** [comment]
http://codepen.io/caalberts/pen/NxpeRP?editors=010

**Comment by zellwk** [comment]
http://codepen.io/zellwk/pen/eJvbYB?editors=010

**Comment by calvintan** [comment]
http://codepen.io/calvintan/pen/VepqaG

**Comment by yongjun21** [comment]
http://codepen.io/yongjun21/pen/rxyomz

**Comment by jerrygraced** [comment]
http://codepen.io/jerrygraced/pen/Vepqrq

**Comment by cbas** [comment]
@caalberts Looks good.

`mediumspringgreen` :laughing: [Amazing how they came up with those names.](https://www.youtube.com/watch?v=ciGmOlxRxeg)

**Comment by cbas** [comment]
@calvintan Nice thanks for demonstrating http://placehold.it/ ... nifty & useful service!

`float: left;` ಠ_ಠ

**Comment by cbas** [comment]
@yongjun21 Sweet! dat `text-align: justify;` tho...

A breakpoint would also make it nice and responsive.

**Comment by cbas** [comment]
@jerrygraced 
# AND HIS NAME IS JOHN CENA

Nice job!

- Avoidable classes
  - Instead of `.section` just use `<section>`
  - `.first` can be `:first-of-type`
  - `.second` can be `:nth-of-type(2)`
- Avoid naming classes after their appearance.
  - `.left` and `.right` are simply alternating content sections. How they are styled does not concern the content structure. Use `:nth-of-type(odd)` and `:nth-of-type(event)` to target them for styling.

**Comment by calvintan** [comment]
Inspired to return to this after discovering 'position: sticky', supported in firefox and safari only: http://codepen.io/calvintan/pen/ZQaOOa

**Comment by cbas** [comment]
@calvintan Awesome! May be interesting to know that Blink/Chrome used to support it as well but was dropped a few years ago. Supposedly still going to be supported with a new implementation. [Source](https://www.chromestatus.com/feature/6190250464378880) (See also the explanation on [StackOverflow](http://stackoverflow.com/questions/15646747/why-doesnt-position-sticky-work-in-chrome).)
