### ISSUE TITLE
Data Attribute

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-organisers#14]
<img width="80" alt="screen shot 2016-01-05 at 10 13 25 pm" src="https://cloud.githubusercontent.com/assets/78718/12117202/1c75f86c-b3fa-11e5-9445-64ac0084c542.png">

# Challenges
1. Use only one `<button>` or `<a>` per share button
1. Orange default colour with blue hover state
1. Elements are only differentiated by class (e.g. `class='facebook'` or `class='twitter'`)
1. Counter is specified using a `data-count='123'` attribute for each share button
1. Use a hi-dpi vector (SVG or font icon) for each icon

# Hint
CSS `::before` and `::after` pseudo-elements can use `attr(...)` in the `content` property.

# Solution
**Do not view until at least half your hair has been pulled out in frustration**
http://www.wordstream.com/blog/ws/2014/10/20/call-to-action-examples

**Comment by caalberts** [comment]
http://codepen.io/caalberts/pen/EPWvwE

**Comment by zellwk** [comment]
http://codepen.io/zellwk/pen/EPWvQL?editors=010

**Comment by ongmin** [comment]
Check out this baby: :hatched_chick: 
http://codepen.io/ongmin/pen/XXMaYE

**Comment by calvintan** [comment]
http://codepen.io/calvintan/pen/adJyLG

**Comment by caalberts** [comment]
@ongmin you can add `<link>` in head through HTML settings on codepen. Click on the gear button next to "HTML".

**Comment by jerrygraced** [comment]
http://codepen.io/jerrygraced/pen/PPvLMm

**Comment by yongjun21** [comment]
http://codepen.io/yongjun21/pen/rxyzpp

**Comment by jsstrn** [comment]
http://codepen.io/jsstrn/pen/LGWjav responsive and clickable

**Comment by ongmin** [comment]
@caalberts thanks albert! I know, but I just wanted to be explicit so when I'm using it as a library and into Atom, I remember them.

**Comment by peonicles** [comment]
http://codepen.io/peonicles/pen/jWBLaV

**Comment by cbas** [comment]
@jsstrn :bow: Omg.

**Comment by cbas** [comment]
@peonicles :hurtrealbad: You glorious madman...

PS: Set the JS settings to Babel to make it work on Safari.

**Comment by cbas** [comment]
@yongjun21 The `shares` attribute should be `data-shares` to be valid HTML. Otherwise a nice, lean implementation.

**Comment by cbas** [comment]
@jerrygraced Looks great! :+1: 

Random `fetch()` :question: :confused:

Looks good here but be careful with `line-height`. It can be off by a few pixels sometimes. Depends on the font rendering engine used by the browser & OS.

**Comment by cbas** [comment]
@calvintan Sweet! Just two things that catch my OCD ... `content: attr(data-count);` is the only line with a white space. :cold_sweat: ... and the counters are juuuuuust off centre. :scream_cat: Otherwise great!

**Comment by cbas** [comment]
@ongmin :chicken: 

`datacount` should be `data-count` for HTML compliance. The `data-` prefix is what lets us create custom attributes that won't conflict with any past, current, or future core attributes in HTML.

Get rid of the `<head>` section from your HTML. Use the pen settings instead:
<img width="686" alt="screen shot 2016-01-06 at 10 48 35 pm" src="https://cloud.githubusercontent.com/assets/78718/12145194/c8ad7236-b4c7-11e5-8473-6348a5f4a511.png">
