### ISSUE TITLE
ECMAScript 2015 (ES6) in Node.js

### ISSUE THREAD

**Issue by jsstrn** [ga-students/wdi-sg-organisers#17]
To use `let` and `classes` in Node without having to transpile your code, run Node.js in "strict mode":
```
node --use_strict <filename.js>
```

Reference: [ECMAScript 2015 (ES6) in Node.js](https://nodejs.org/en/docs/es6/)

NB: _this is neither a **topic** nor an **exercise**. Perhaps we should have another label for **tips**?_

**Comment by cbas** [comment]
Label: Today I Learned

**Comment by cbas** [comment]
Can share these in class during retrospective.

**Comment by caalberts** [comment]
npm in ES2015 with Babel: https://github.com/caalberts/teeny-weeny-router
