### ISSUE TITLE
Google API 6 Jan - Lesson Postponed

### ISSUE THREAD

**Issue by Tianster** [ga-students/wdi-sg-organisers#19]
@rachlim @cbas @sevresbabylone  - Just want to put this as a reminder

**Comment by rachlim** [comment]
@Tianster Thank you, TIan! @cbas @sevresbabylone @zellwk when can I reschedule it on the calendar?

**Comment by cbas** [comment]
Lesson replaced. Can set up an exercise to explore this API as homework. Also would appreciate contribution as a TIL.
