### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-organisers#2]
*Note: Migrating this thread from email to GitHub Issues for transparency.*

@rachlim wrote:

> Hey all! 

> So sorry to work-email you guys during your holidays- really hope you are enjoying the break! 

> Here are several things that we are going to work on for the new term, that hopefully minimise pressure/workload on all of you by being more efficient and ensuring more effective learning on the part of the students. The main objective of this is to improve the skills/learning experience of the struggling students, teaching/instruction as you normally go about it will continue, Seb! I'm aware that some of it is not ideal but it's what we have to work with and I'm really looking forward to working as closely with you guys as possible on this! 

> 1. **Half-half Teaching/Labs Split**
> As a result of a lot of feedback indicating that they would like more labs and hands-on activity, class will be divided into teaching in the morning based on objectives set for the day (plus whatever cool live coding/activities Seb has in mind) and labs/hands-on or wax-on, wax-off activities in the afternoon that are tied to those objectives. 

> 2. **Class Split**
> During labs, students will be split into 2 groups, the struggling students and the faster students. The struggling students will go into a circle at the side of the room where Zell will go over the days objectives + basic knowledge (e.g functional Javascript) again, in step-by-step, structured way. I know Seb and Cheryl, you are concerned about managing the rest of the class, but this is the best way we can cater to the different learning styles without leaving people significantly behind. Let's try this for 2-3 days first, and then check-in to see how we can improve it? 

> 3. **Project Structure**
> We'll start implementing more structure to the projects (for the weaker students). I think Seb's style of 'anything goes' worked super well for the faster students and if you'd like, we can maintain that around certain parameters. For the struggling students, we'll pair them up with one another and have a very specific project they'll be working on (maybe even the same project) that they can be helped with along the way. We'll share out the project guidelines and parameters on Friday mornings after which they can start thinking about it and planning with your guidance, going back on the weekend to experiment and really getting into it on Monday. Fridays will be for presentations for all, no matter where they are on their projects. 

> 4. **Planning**
> We'll sit down on Monday or Tuesday (if you guys are free?) to talk about the different objectives Seb wants to cover for the remaining three weeks and to plan out how it will look with the inclusion of labs. Things we will consider: objectives not yet covered + objectives to recap/revise. We have roughly 13 more lessons, counting project week and project prep Fridays! 

> 5. **Speakers**
> While the speakers so far have been amazing and really added breadth to what the students are learning, we need to focus more on labs and classes for the next few weeks so the students get as much guided hands-on experience as needed, and if speakers do come in, it should ideally happen over lunch/for shorter time periods, once/twice a week. If speakers have already been arranged for class time and it's not an absolutely need-to-know skill, we can structure it such that the struggling students go out for their labs during the sessions. 

> Again, I'm so sorry to disturb you guys on holiday, and I really do hope that this is okay for all of you. Do let me know if there are aspects you think can be done better or more efficiently and let's talk about that! We're all on the same side and the goal at the end of this is to equip our students with developing skills, even if we may not necessarily be creating developers immediately. 

> Seb, if you could think about what you want to do next week, maybe for the first two-three mornings and what exercises you'd like them to do in the afternoons (if you have more time, maybe recap exercises or codealongs?), I will add that into the calendar (: 

> Thank you, everyone! 

> Regards,
> Rachel   

@cbas wrote:

> Hi Rachel,

> Appreciate the suggestions. Always keen to try more experiments on the class and see what works.

> 1. This worked great in the last week or two. Glad the feedback confirms our intuition. Would like to split each day into quarters: lesson/lab & lesson/lab. Doing a lesson for more than an hour tends to lose a lot of the students. The more granular the lessons, the better IMO. Have taught many mini-lessons during exercises and projects and they seem to stick with the students.

> 2. Parity is not my concern. That means I'm happy to split the class in half (or even smaller segments, even down to the individual level). Also means I'm happy the faster students go waaaay beyond the rest (as they have). Let's help everyone learn as much as they can. Hard to do this during a lecture-style class. Works well during labs with many smaller impromptu lessons based on missing skills we discover in specific students. One thing to watch out for is the self-fulfilling prophecy of dividing people into "weaker" and "stronger" groups. This is detrimental to both groups.

> 3. That's almost exactly much what we did on the second project. What totally failed was pairing weaker students together. No amount of coaching other than 100% dedication was enough. We don't have enough coaching bandwidth so I'd like to try pairing weaker and stronger students instead. This worked very well for some pairings. As far as "structure" is concerned, it’s important that students learn to solve problems, not just follow instructions. Programming requires an enormous capacity for creative thinking.

> 4. What do you mean by roughly 13 more lessons? There are a number of important topics I'd like to cover in the coming 5 weeks. These would certainly be useful to anyone who wants to be a programmer. Can you mark on the shared calendar which days are *not* available for lessons? I thought we'd have project week 9 & 12 but the remainder would be lesson weeks. I'll work on a list of topics.

> 5. Speakers have been hit & miss. Mostly hit, which is why I continued inviting them. I think the last one had students sleeping in their chairs, watching videos, and completely uninterested. Frankly I didn't enjoy that session either. However a few of the students looked extremely interested. Most of the other speakers have been amazingly well received by the class. Could this be an issue with the content?

@rachlim wrote:

> Hey Seb! 

> Thanks for the email and thought put into it- I do genuinely feel the majority of the class is doing amazing and I'm always so blown away by how inspired and encouraged they are in the class. 

> 1. LOVE this suggestion! Let's do this! 
> 2. Yeah- I'll talk to the students about following Zell during the labs as a 'structured learning' group, and those who feel they might benefit from it can sit in if they so wish. It won't be segregating, more of differentiated learning. 
> 3. I think pairing weaker and stronger students can result in the weaker student not really trying as much as the stronger student doesn't have the time/level of understanding to stop and explain things; particularly if the weak/strong divide is too large. Do you think it might work better if we paired the struggling students up, and for the other students paired weak/strong but gave them closer attention and made the objectives easier/more scaffolded? We can assign pairings next week, say Wednesday before we give them the brief on Friday?
> 4. Oh, when I said 13 lessons I assumed it would be chunked into morning teaching/afternoon labs. But breaking days into quarters would give us 26 lessons! I'll mark into the calendar right now- but for clarification, non-lesson days would the two Fridays before project week (as pre-project prep and discussion) and the project weeks. Which gives us 3 weeks - 2 days remaining, so 13 days. 
> 5. I think speakers have been great, and most of the students agree but in their 1:1 feedback many have said they would rather spend the time practising/coding- perhaps we can find a happy balance for this by having fewer, and also I think making certain speakers' sessions optional especially for the struggling students. What do you think?

> Regards,
> Rachel

**Comment by cbas** [comment]
@rachlim Thanks for the calendar updates. :heart: 

Why change project presentations to Friday? Last time we did presentations on Monday and Tuesday mornings. Worked quite well, I thought, as it allows an extra weekend to polish the project. Also doing two stages helps for teams who just want a little extra time to polish things.

**Comment by rachlim** [comment]
@cbas You're welcome!

The thinking behind this was twofold, 
1. That we are introducing projects in the week before (Friday) so they now have that weekend to work on it after initial advice and discussion, giving them a total of 7/8 days to work on the projects- same time! Presentations could be done in the afternoon after lunch, perhaps?
2. Given we have only got 3 weeks remaining (and 13 days of classes) it would be best to maximise those times for classes and keep projects to project weeks (particularly as the final week ends on a Friday and they will have to present on that Friday itself! 

Also, I think confining projects to project week make the whole process clearer and more structured- after that week, if students want to work on their projects on their own time to further polish etc. that's fine but class time will be for class. Sound okay?

**Comment by rachlim** [comment]
@cbas I've also done a draft schedule on the calendar for the quarter lesson/lab on Monday 4th Jan- is this time division okay by you? I can just replicate it across the rest of the days and you can fill in objectives when you decide what they are (: Let me know if you think the timings ought to be changed. Aziza also needs a 1.5 hour block for Outcomes sessions (talking CVs/Portfolios etc) on Thursday/Friday- if you think cannot afford to give up lesson time on Thursday we can do Friday after project brief!

**Comment by cbas** [comment]
##### Calendar
Reasoning makes perfect sense now. Hadn't realised the last project week doesn't have a Monday to follow up. :confounded: :cry: 

I further divided the mornings to start with a retrospective (daily news, show & tell, etc). Also works as a buffer but I'll make sure it starts on time and adds value to prevent slippery slope of latecomers.

#### Project Week / Hackathon
What we did on project 2 was to turn the Friday before project week into a "hackathon." Teams were adjusted a bit on Monday but it was useful to iterate the project.

![Iteration](http://blog.deming.org/wp-content/uploads/2014/11/minimal-viable-product-henrik-kniberg.png)

#### Outcome Sessions
Please mark these slots on the calendar if/once they're confirmed.

**Comment by rachlim** [comment]
@cbas Have input the outcomes session for next week into the calendar! We might do the next one after presentations on Project 3 week, depending how fast presentations go (might want to think up a general structure of presentations for students to follow?). 

About the Hackathon: I think it's a great idea for the faster students, but for the students who are still struggling it might seem a bit overwhelming and difficult as they sometimes are not so familiar with the basic skills/libraries/frameworks/standards needed to effectively and efficiently execute a Hackathon. Might I suggest we split this activity into two groups as well- with the faster students following the Hackathon structure and the struggling students following a more structured project outline, working on the foundations of their project in pre-set pairs under @zellwk?

**Comment by Tianster** [comment]
@cbas @rachlim 
Hi All,
I noticed this thread is only 6 days old. Wondering if you guys have discussed anything regarding course materials given out in advanced before or during the break? I don't see them being discussed here. And I see MVC is added in the calendar after someone requested for it. 

Seb, you mentioned Parity is not your concern. While I understand that all of us are of different programming calibre and it is easier to teach those who have programming background, I sincerely hope you rethink your stance. I decided to come to a reputable school like GA with certain expectations that I will get a reasonable education in web development in a structured way. I fully agree that everyone wants to learn as much as they can if not they wont be spending full day at the school. But I am overwhelmed by the sheer amount of unstructured information given to us. I'm sure Rachel can elaborate on this as I have discussed with her at length. 

I am afraid I don't understand what Seb's wrote: "As far as "structure" is concerned, it’s important that students learn to solve problems, not just follow instructions. Programming requires an enormous capacity for creative thinking."  I am wondering whats the underlying message here? 

We are all working adults and exercise certain amount of creative thinking and use problem solving skills 
during the course of our professional lives. We were methodically trained / drilled in school or on the job to approach any problems with a certain set of best practises involved. Yes, there are times when emergencies arise, that is when our strong foundation in whichever subject matter comes into play. 

Thanks and good night. 

T

**Comment by cbas** [comment]
@Tianster Of course. Plan for change. Gradual introduction of concepts. We've all come very far over the past few weeks, not least of all you. I'm very proud of the progress, especially yours.

Everyone is in the same class. How long one takes to grok information depends on curriculum & teaching style but also on students' prior experience & knowledge. I have not yet seen a school where every student graduates with the same exact, absolute level of experience and knowledge. Rather than paralysis or retreat, continue to work and learn at your own pace. Myself and the team are always there for you. Thanks for making use of the additional classes provided over the holidays.

There are no silver bullets, no panacea. What's being refactored here is the structure of the class, to better align with this specific and varied group of individuals at this specific intersection of time in their lives.

Keep up the hard work!

**Comment by cbas** [comment]
Further refactoring:

# CSS Breakfast (& Lunch!)
Every time we come back to class we'll start off with a bite-size exercise. Rewards punctuality. Maximises available time. Gets everyone in the right frame of mind to code & learn.

Prep work for the exercises consists of small screenshots and a GitHub Issue on this repo labelled [`exercise`](https://github.com/ga-students/wdi-sg-organisers/issues?q=label%3Aexercise). Anyone is welcome to propose exercises. See example: #11

**Comment by cbas** [comment]
Review: Seems to work well so far this week.
