### ISSUE TITLE
Sliding Menu

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-organisers#20]
<img width="545" alt="screen shot 2016-01-08 at 9 58 28 am" src="https://cloud.githubusercontent.com/assets/78718/12188257/6ba90dfc-b5ee-11e5-8984-b3ff302e91e6.png">

**Comment by zellwk** [comment]
http://codepen.io/zellwk/pen/gPWrZW?editors=010

**Comment by tongrhj** [comment]
Seems like its pretty much what Zell did: http://codepen.io/tongrhj/pen/WrjwBJ

**Comment by cbas** [comment]
@tongrhj Made some changes in a fork http://codepen.io/cbas/pen/xZdOdV

- Cleaned up syntax (Stylus & JS)
- Added a `:before` overlay to the button. This should improve UX by focusing attention on the menu, and prevents accidentally clicking in the main content area. Can further improve this with a `<label>` for the button to make clicks in the main content close the menu.
