### ISSUE TITLE
Dropdown Menu

### ISSUE THREAD

**Issue by alyssaq** [ga-students/wdi-sg-organisers#21]
![menu](https://cloud.githubusercontent.com/assets/2819448/12188767/3a20810c-b5f3-11e5-9e41-ce1b2a81bafc.png)

Menu icon (globe in the screenshot) should be a font. Use something like [fontastic](http://fontastic.me/).
Dropdown appears on click of the icon.

**Comment by cbas** [comment]
:+1:

**Comment by cbas** [comment]
http://codepen.io/cbas/pen/gPWwZO

**Comment by jsstrn** [comment]
My solution requires JavaScript http://codepen.io/jsstrn/pen/BjRLgj

**Comment by calvintan** [comment]
http://codepen.io/calvintan/pen/eJWdQe

**Comment by alyssaq** [comment]
OMG its all so good! Thanks guys!
My solution doesnt even come close to any one of yours :disappointed: 
@cbas & @calvintan, I like how you guys added a shadow to the dropdown when it was just a background :p
@jsstrn yay! Your first & last menu item hover doesnt overflow the menu.

**Comment by tongrhj** [comment]
For our 9GAG clone, I changed the height, opacity and visibility of the dropdown menu on hover of the button! :older_man: http://tongrhj.github.io/wdi-sg-9GAG

**Comment by yongjun21** [comment]
http://codepen.io/yongjun21/pen/adWmRG

**Comment by caalberts** [comment]
http://codepen.io/caalberts/pen/wMdzZG/?editors=001 :boom:

**Comment by alyssaq** [comment]
@tongrhj Ooooh sweet!
@yongjun21 I like your solution using :focus since the menu hides when you click elsewhere. Just needs a rounded border.
@caalberts :open_mouth: So damn cool!!

**Comment by jerrygraced** [comment]
http://codepen.io/jerrygraced/pen/xZdEBa

**Comment by alyssaq** [comment]
@jerrygraced Love the pun and emojis! Minor thing, the `<li>` elements should have either a `<ul>` or `<ol>` parent.

**Comment by shawnlimws** [comment]
http://codepen.io/shawnlimws/pen/gPWwBY?editors=010

woo!

**Comment by alyssaq** [comment]
@shawnlimws woo!  I noticed that both the nav and arrow's visibilities are toggled on click. Since those elements are wrapped in a container, the code can be simplified to toggle only the container's visibility.

**Comment by shawnlimws** [comment]
@alyssaq oh yeah! I saw this two yesterday and was in the midst of changing it but fell asleep. shall work on it now. Thanks for pointing it out! :)
