### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by zellwk** [ga-students/wdi-sg-organisers#23]
Suggested by @yongjun21
http://codepen.io/yongjun21/pen/VebMrY?editors=100

**Comment by cbas** [comment]
My absolutely perfect awesome super amazing solution:
http://codepen.io/cbas/pen/PZjqNq?editors=110

**Comment by yongjun21** [comment]
:bow: :bow: :bow:

**Comment by zellwk** [comment]
My weird + unique solution: http://codepen.io/zellwk/pen/bEYRbV

**Comment by shawnlimws** [comment]
Best I could do.. 

http://codepen.io/shawnlimws/pen/rxYwBG?editors=010

**Comment by AlvinderSingh** [comment]
http://codepen.io/AlvinderSingh/pen/OMOmoe

**Comment by dedyrk** [comment]
http://codepen.io/dedrock/pen/LGOyqr

**Comment by weejh** [comment]
http://codepen.io/weejh/pen/wMPdOv

**Comment by sevresbabylone** [comment]
Checking part doesn't work
http://codepen.io/sevresbabylone/pen/qbVjaQ

**Comment by peonicles** [comment]
http://codepen.io/peonicles/pen/JGONeL?editors=101 (WIP)

**Comment by mel1313** [comment]
http://codepen.io/anon/pen/PZOjWq
