### ISSUE TITLE
Checkbox toggle

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-organisers#25]
![Checkboxes](http://zippy.gfycat.com/BabyishNeedyDeviltasmanian.gif)

# Tips
- Use the non-standard `appearance: none;` to reset the native look & feel. Alternatively hide the element using `display: none;` or any other technique we've used before.
- An `<input type='checkbox'>` is toggled when a containing `<label>` is pressed.
- Use the `:checked` pseudo-class, optionally with `:not(:checked)` inversion.
- Maybe look into `+` or `~` [sibling selectors](http://www.w3.org/TR/css3-selectors/#sibling-combinators).

# Source
Not a solution, just a UX mockup animation.

http://gibbon.co/c/d5a67253-2672-4a97-82c3-d69ebcf99b1c/life-at-khan-academy

**Comment by cbas** [comment]
http://codepen.io/cbas/pen/KVXjZy?editors=110

**Comment by sevresbabylone** [comment]
http://codepen.io/sevresbabylone/pen/RrLzJr

**Comment by lanbau** [comment]
http://codepen.io/lanbau/pen/GoMbGq

**Comment by tongrhj** [comment]
Because I initially chose to style the label rather than the span within the label, I'm now facing difficulty changing the border colour when the input is checked! http://codepen.io/tongrhj/pen/KVXjmX

**Comment by cbas** [comment]
@lanbau Looking good. Couple of remarks:
- Be consistent (OCD-level) with white space in the CSS/HTML.
- LI can only exist inside OL or UL. Not randomly inside any elements; that's what SPAN/DIV are for (non-semantic markup).

**Comment by cbas** [comment]
@tongrhj 
- Target the parent using `!` (CSS level 4 ... not sure if supported anywhere yet) https://www.w3.org/TR/selectors4/#subject
- The Jade template generates duplicate IDs.
- Outline on the checkbox is a bit weird. Should be on the entire target?
- Use autoprefixer from the CSS settings for the `-webkit-appearance: none;` vendor prefix.
- Use semantic names for the colours. Otherwise the purpose is defeated. `$checkboxblue` can just be `$checkboxActive` so you won't need to update the variable names everywhere when the designer changes their mind.

**Comment by tongrhj** [comment]
ok updated! thanks @cbas.

* Used javascript to select the parent label element instead
* Setting `outline: 0` on the label element removed the strange blue outline around the checkbox

**Comment by calvintan** [comment]
A combination of today's exercises... http://codepen.io/calvintan/pen/gPGVbW

**Comment by yongjun21** [comment]
http://codepen.io/yongjun21/pen/XXzGyP
