### ISSUE TITLE
Ligatures

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-organisers#27]
Turn text into pictograms using font icons and ligatures.

# Typographical ligatures 
![Typographical ligatures](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Ligatures.svg/2000px-Ligatures.svg.png)

# Icon Font Ligatures Hack
[![](http://kendsnyder.com/wp-content/uploads/2014/08/post-22754056.png)](http://kendsnyder.com/why-you-should-consider-a-ligature-icon-font-for-your-next-project/)

# Example
http://codepen.io/cbas/pen/EPvLwg?editors=110

**Comment by shawnlimws** [comment]
Hahah.. 

http://codepen.io/shawnlimws/pen/JGrQxg

**Comment by lanbau** [comment]
https://codepen.io/lanbau/pen/XXevbw?editors=110

**Comment by peonicles** [comment]
http://codepen.io/peonicles/pen/MKEMxq

**Comment by ongmin** [comment]
http://codepen.io/ongmin/pen/qbPzGB

**Comment by cbas** [comment]
@shawnlimws Love the background effect!

- It's possible to use CSS settings on Codepen to take the `link` out of the editor box.
- `.text` and `.apparatus` classes are not used anywhere.

**Comment by cbas** [comment]
@lanbau Nice animation :+1: 

- Have a stab at making the animation loop forever.

        animation-iteration-count: infinite;
        animation-direction: alternate;

- Watch the white space consistency.

- Not actually a ligature; more of an icon font. Ligature means you're using the text (in HTML) associated with the glyph.

**Comment by cbas** [comment]
@peonicles Sweet effect :)

- Why manually resetting the counter? Can use module (`%`) to keep wrapping.
- Could also use CSS to achieve the effect without JS.

**Comment by peonicles** [comment]
@cbas won't the counter overflow eventually if i keep adding ?

**Comment by cbas** [comment]
@ongmin Very cool ...

- What are the `msl` and fs1

**Comment by ongmin** [comment]
@ongmin removed, they were leftover from iconmoon's export to codepen function.
