### ISSUE TITLE
Multiple Columns

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-organisers#28]
<img width="1067" alt="screen shot 2016-01-28 at 1 10 35 am" src="https://cloud.githubusercontent.com/assets/11501546/12621664/87cb02c4-c55c-11e5-91bd-3a096605c0e2.png">

Make a section detailing your brief history (or just use Lorem Ipsum) using column-count, column-width to create a old-school print-inspired layout. 
- Try to make it Responsive Friendly
- Try to make it look nice and customise it to your own liking

Check out:
[CSS Tricks: Guide to Responsive-friendly Columns](https://css-tricks.com/guide-responsive-friendly-css-columns/)
[CSS Tricks: break-inside](https://css-tricks.com/almanac/properties/b/break-inside/)

If you want to follow this design which I did not come up with myself, 
Font is "Roboto Slab" from Google Fonts
background color: #fbfbfb
title font color: #333 
text font color: #444
gray top and bottom border: #d6d6d6

and [text-shadow properties](https://css-tricks.com/almanac/properties/t/text-shadow/)

**Comment by zellwk** [comment]
@cbas are you thinking multiple columns with CSS Grids or CSS Columns? :)

**Comment by cbas** [comment]
I was thinking of good old [`column-count` / `column-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Using_multi-column_layouts). I don't think [CSS Grids](http://www.w3.org/TR/css-grid-1/) are stable enough, though worth a mention (again).

**Comment by zellwk** [comment]
CSS Grids aren't stable yet, which is why I haven't look into it. We could talk about good ol' `column-count` and `column-width` then. Will work on it

**Comment by zellwk** [comment]
![screen shot 2016-01-25 at 12 27 02 am](https://cloud.githubusercontent.com/assets/3607637/12537441/67c8aa58-c2fa-11e5-8ae7-4c913cb6f310.png)

**Hints:**

[column](https://css-tricks.com/almanac/properties/c/columns/)

**Comment by zellwk** [comment]
http://codepen.io/zellwk/pen/RrypZz
