### ISSUE TITLE
:selection

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-organisers#31]
![clipboard](https://cloud.githubusercontent.com/assets/11501546/12453999/90f2df2a-bfd0-11e5-821b-4fd9be9e5a97.jpg)
Purple: #775899
Yellow: #ffc444
font-family: Avenir

Make a copy-to-clipboard bar where the highlighted text has a different color/style than the default blue highlight

Bonus: Copying to Clipboard doesn't work in Safari. Find a way to tell safari users to hit Cmd + v

hints: document.execCommand , :selection

[Possible Solution](http://codepen.io/sevresbabylone/pen/bEaEEr)

**Comment by tongrhj** [comment]
@yongjun21 was screaming profanities at me the whole time :( http://codepen.io/tongrhj/pen/WrdjEW

**Comment by ongmin** [comment]
http://codepen.io/ongmin/pen/pgpwzy

**Comment by zellwk** [comment]
Jesstern's answer: http://codepen.io/zellwk/pen/ZQvKrQ

**Comment by mel1313** [comment]
http://codepen.io/anon/pen/NxXjMV
Interview Passed! :bowtie:

**Comment by cbas** [comment]
@mel1313 Captain Anonymous passed the interview -- no proof it was you :stuck_out_tongue:

**Comment by shawnlimws** [comment]
http://codepen.io/shawnlimws/pen/Goymbz?editors=010

**Comment by sevresbabylone** [comment]
Thanks everyone for the answers. Looks like most people managed to get the copy function to work. Good job!

**Comment by mel1313** [comment]
@cbas. . . :rage:

**Comment by sevresbabylone** [comment]
@shawnlimws   
```window.clipboardData.setData('Text', text)``` doesn't work for me. Seems to be deprecated. https://msdn.microsoft.com/en-us/library/ms535220(v=vs.85).aspx 

 ```
align-items: center;
justify-content: center;
```
not necessary as you want the child elements to be next to each other. 

Looks great though!

**Comment by sevresbabylone** [comment]
@mel1313 
```
.inputCopy {
  display: flex;
  margin-top: 100px;
  margin-left: 200px;
}
```
You could use margin: 0 auto; to centre the element, it was just not working as .inputCopy doesn't have a specified width and was filling up the full width of the screen so it was already centred. using margin-left would just push it to the left and out of the screen.
