### ISSUE TITLE
Form Input Validation

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-organisers#32]
<img width="1004" alt="screen shot 2016-01-22 at 8 58 13 am" src="https://cloud.githubusercontent.com/assets/11501546/12499539/66cc7046-c0e6-11e5-90a2-370fb81b7f17.png">
Make a form and try :required :optional pseudo classes
Cannot style input:required:before as input element is empty

(if you want to follow the styles)
```
@import url(https://fonts.googleapis.com/css?family=Varela+Round);
```

Body background: #c0c0c0
Green button colour: #33cc77
Pinkish red: #ffc3c3
Grey font colour: #777

http://codepen.io/sevresbabylone/pen/gPoBjB

**Comment by shawnlimws** [comment]
http://codepen.io/shawnlimws/pen/dGJENW?editors=1100
my form! :)

**Comment by peonicles** [comment]
http://codepen.io/peonicles/pen/zrpQqG?editors=1100

yay

**Comment by chuckberry1974** [comment]
http://codepen.io/chuckberry007/pen/WrdBeg?editors=1100

**Comment by weejh** [comment]
http://codepen.io/weejh/pen/JGMqWR/?editors=1100

**Comment by calvintan** [comment]
http://codepen.io/calvintan/pen/adErpN

**Comment by tongrhj** [comment]
http://codepen.io/tongrhj/pen/LGevwN

**Comment by yongjun21** [comment]
http://codepen.io/yongjun21/pen/vLpwmW

**Comment by mel1313** [comment]
http://codepen.io/anon/pen/obpRyG

**Comment by RoyKoh** [comment]
http://codepen.io/RoyKoh/pen/pgpmoG  
will continue to work on the click validation
