### ISSUE TITLE
Design Patterns in JavaScript (MVC)

### ISSUE THREAD

**Issue by jsstrn** [ga-students/wdi-sg-organisers#6]
The idea behind developing applications using a design pattern like Model-View-Controller (MVC) is to separate our code (referred to as separation of concerns).

**The Model** handles the data of your application. 
**The View** handles the presentation of your application.
**The Controller** handles the logic of your application.

The MVC architecture is used in mobile and web application development and I think it is a very useful architecture to learn in our journey to becoming web developers.

**Comment by jsstrn** [comment]
I am wondering how we might use MVC in JavaScript. Would the following structure be considered best practice?

```
(function () {
  const model = {
    init: function () {...}
  },
  const view = {
    init: function () {...}
  },
  const controller = {
    init: function () {...}
  }
  controller.init()
})()
```

I suppose they can each be placed in separate files (I'm not sure).

**Comment by cbas** [comment]
:+1: Let's work more on project structure, layout, architecture. Will cover MVC in that context.

**Comment by cbas** [comment]
We started getting into this project structure with the router refactoring today. Will continue over the next few days as we grow the app in complexity.
