### ISSUE TITLE
Suggested Topic: Regular Expressions

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-organisers#7]
@jsstrn Did you have a really good tutorial for RegEx?

**Comment by jsstrn** [comment]
@cbas Yes, as a matter of fact, I do: http://regexone.com/

**Comment by cbas** [comment]
:+1: Thanks for the link!

**Comment by cbas** [comment]
Use case demo: http://codepen.io/cbas/pen/NxdZpm

**Comment by cbas** [comment]
Anti-use case: http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags

**Comment by jsstrn** [comment]
Other stuff shared during the lesson:

- `/((\+|00)?65[\.\-\s]?)?\d{4}[\.\-\s]?\d{4}/` regex to match phone numbers in SG
- https://regexcrossword.com/
- https://regex101.com/

**Comment by cbas** [comment]
Thanks for the help @jsstrn :+1:
